### ISSUE TITLE
RSS reader can't view any images or see actual blog post link

### ISSUE THREAD

**Issue by descrip** [dimview/dimview.github.io#2]
Using Feedly, I can't view any images or follow the link of any blog post, except for the most recent one. The same happens when trying to view the feed in Firefox:

![screenshot from 2018-02-19 01-36-07](https://user-images.githubusercontent.com/6173806/36365036-a0db5056-1515-11e8-8f9d-9e4a2c9e63f6.png)

Note that the first entry links to the blog post, while the rest of them don't.

I think this might be because of your relative URLs.

**Comment by dimview** [comment]
I added url to Jekyll configuration file and can now see links in RSS in Firefox. Could you please check if it works in Feedly?

**Comment by descrip** [comment]
It does, thank you!

(Actually, Feedly still has problems, since I think they cache blog posts, so we'll have to wait and see when they refresh. On other RSS readers that don't bother to cache anything, the links show up fine.)
